# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PipelineBLE' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PipelineBLE
  pod 'CocoaMQTT', '~> 1.1.2'
  pod 'MSWeakTimer', '~> 1.1.0'
  pod 'UIColor+Hex', '~> 1.0'
end
